# Generated by Django 4.2 on 2023-07-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=11, verbose_name="Amount"),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Purchase"), (1, "Charge")],
                        default=2,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "paid"), (0, "pending"), (-10, "Not paid")],
                        default=-10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created Date"),
                ),
                (
                    "invoice_number",
                    models.UUIDField(default=uuid.uuid4, verbose_name="Invoice number"),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="package.package",
                        verbose_name="Package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET("deleted_user"),
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
