# Generated by Django 4.2 on 2023-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "advertisement",
            "0002_alter_category_options_advertisement_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Price"),
        ),
    ]
