# Generated by Django 4.2 on 2023-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0004_alter_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
    ]
