# Generated by Django 4.2 on 2023-07-20 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advertisement", "0006_alter_advertisement_image_bookmark"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("advertisement", "user")},
        ),
    ]
